# Generated by Django 4.0.4 on 2022-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('postalzip', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('alphanumeric', models.IntegerField()),
            ],
        ),
    ]
