# Generated by Django 4.0.4 on 2022-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='postalzip',
            field=models.CharField(max_length=200),
        ),
    ]
